theme: jekyll-theme-cayman
plugins:
  - jekyll-relative-links
  - jekyll-sitemap
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
  
  
 navbar-links:
    About: "about"
    Resources:
      - Contact: "contact" 
      - Timeline: "timeline"
    Announcements: "announcements"
    My GitHub: "https://github.com/hsoyka"

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-children-col: "#F5F5F5"
